# -*- coding: utf-8 -*-
"""TGbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9gVPIlcxjDwlSC2rZtA8U-6s0U-XxwM
"""

pip install python-telegram-bot

pip install python-telegram-bot

from telegram import Update
from telegram.ext import Updater, CommandHandler, CallbackContext

# Вставьте ваш токен сюда
TOKEN = '7556644113:AAH8mjPNwjX-CMcLlWdbf6FCNcWwMDLRuEY'

#!/usr/bin/env python
# pylint: disable=C0116,W0613
# This program is dedicated to the public domain under the CC0 license.

"""
Simple Bot to reply to Telegram messages.

First, a few handler functions are defined. Then, those functions are passed to
the Dispatcher and registered at their respective places.
Then, the bot is started and runs until we press Ctrl-C on the command line.

Usage:
Basic Echobot example, repeats messages.
Press Ctrl-C on the command line or send a signal to the process to stop the
bot.
"""


from telegram import Update, ForceReply
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, CallbackContext




# Define a few command handlers. These usually take the two arguments update and
# context.
def start(update: Update, context: CallbackContext) -> None:
    """Send a message when the command /start is issued."""
    user = update.effective_user
    update.message.reply_markdown_v2(
        fr'Hi geek',
        reply_markup=ForceReply(selective=True),
    )


def help_command(update: Update, context: CallbackContext) -> None:
    """Send a message when the command /help is issued."""
    update.message.reply_text('Пошел нахуй со своей помощью!')

def mychannel_command(update: Update,context:CallbackContext) -> None:
  update.message.reply_text('@metsuki_sutemi888')


def main() -> None:
    """Start the bot."""
    # Create the Updater and pass it your bot's token.
    updater = Updater("7556644113:AAH8mjPNwjX-CMcLlWdbf6FCNcWwMDLRuEY")

    # Get the dispatcher to register handlers
    dispatcher = updater.dispatcher

    # on different commands - answer in Telegram
    dispatcher.add_handler(CommandHandler("start", start))
    dispatcher.add_handler(CommandHandler("help", help_command))
    dispatcher.add_handler(CommandHandler("profile", mychannel_command))


    # Start the Bot
    updater.start_polling()

    # Run the bot until you press Ctrl-C or the process receives SIGINT,
    # SIGTERM or SIGABRT. This should be used most of the time, since
    # start_polling() is non-blocking and will stop the bot gracefully.
    updater.idle()


if __name__ == '__main__':
    main()